version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/adapter/**"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
